trigger:
    - master

pool:
    vmImage: "Ubuntu-16.04"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "10.x"
      displayName: "Node.js"

    - script: |
          npm install
          npm run tcm
      displayName: "Prepare"

    - script: npm run tslint-ci
      displayName: "TSLint"

    - script: npm run start-ci
      displayName: "Build"
      failOnStderr: true

    - script: npm run test-ci
      displayName: "Test"

    - task: PublishTestResults@2
      displayName: "Test report"
      condition: succeededOrFailed()
      inputs:
          testRunner: JUnit
          testResultsFiles: "**/junit.xml"
