trigger:
    - master

pool:
    vmImage: "Ubuntu-16.04"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "14.x"
      displayName: "Node.js"

    - script: npm install
      displayName: "Install"

    - script: npm run bootstrap
      displayName: "Bootstrap"
      env:
          CI: true

    - script: npm run tslint-ci
      displayName: "TSLint"

    - script: npm run test-ci
      displayName: "Test"

    - task: PublishTestResults@2
      displayName: "Test report"
      condition: succeededOrFailed()
      inputs:
          testRunner: JUnit
          testResultsFiles: "**/junit.xml"
