trigger:
    - master

pool:
    vmImage: "Ubuntu-16.04"

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "10.x"
      displayName: "Install Node.js"

    - script: |
          npm install
          npm run tcm
          npm start
      displayName: "npm install and start"

    - script: npm test
      displayName: "npm run test-ci"

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
          testRunner: JUnit
          testResultsFiles: "**/junit.xml"
