on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install
        run: npm install

      - name: bootstrap
        run: npm run bootstrap

      - name: docgen
        run: npm run docgen

      - name: build
        run: npm run docs-build

      - name: upload
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: deploy
        uses: actions/deploy-pages@v3
        with:
          token: ${{ github.token }}
